language: php

sudo: required

services:
  - mysql

env:
  global:
    - GLPI_SOURCE="https://github.com/glpi-project/glpi"
    - CS=7.2
    - DBUSER=root
    - DBNAME=glpitest
    - OLDDBNAME=glpiupgradetest
    - AFTER_SUCCESS_BRANCH=9.4/bugfixes
  matrix:
    - GLPI_BRANCH=9.3.0
    - GLPI_BRANCH=9.3/bugfixes
    - GLPI_BRANCH=9.4/bugfixes
    - GLPI_BRANCH=9.5/bugfixes
#    - GLPI_BRANCH=master
    
php:
#  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly
  
# Permit failure on PHP nightly until Travis fix missing gd extension
matrix:
  exclude:
#    - php: 5.6
#      env: GLPIVER=master
#    - php: 5.6
#      env: GLPIVER=9.4/bugfixes
  allow_failures:
    - php: 7.4
    - php: nightly
    
before_script:
  - composer self-update
  - composer require --dev atoum/atoum
  - git clone --depth=1 https://github.com/glpi-project/glpi -b $GLPIVER ../glpi && cd ../glpi
  - sed -e '/"php":/d' -i composer.json
  - sed -i 's/CssMin/cssmin/;s/Faker/Faker/;s/vfsStream/vfsstream/' composer.json
  - composer install --optimize-autoloader --no-dev
  - rm -f composer.lock
  - mysql -u root -e 'create database glpitest;'
  # Both 9.3 and 9.4:
  - if [[ -f "scripts/cliinstall.php" ]]; then php scripts/cliinstall.php --db=glpitest --user=root --tests; else bin/console glpi:database:install --config-dir=./tests --no-interaction --db-name=glpitest --db-user=root; fi
  - mv ../gappessentials plugins/gappessentials
  - cd plugins/gappessentials
  - composer install -o

script:
  - vendor/bin/robo --no-interaction code:cs
  - mysql -u root -e 'select version();'
  - ./vendor/bin/atoum --debug -bf tests/bootstrap.php -d tests/units/

cache:
  directories:
    - $HOME/.composer/cache

#notifications:
#  irc:
#    channels:
#      - "irc.freenode.org#channel"
#    on_success: change
#    on_failure: always
#    use_notice: true
#    skip_join: true
